apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq
  namespace: azure-iot-operations
spec:
  endpointType: mqtt
  mqttSettings:
    host: "aio-mq-dmqtt-frontend:8883"
    tls:
      mode: Enabled
      # NOTE this is where we put the server cert configmap value
      trustedCaCertificateConfigMapRef: aio-ca-trust-bundle-test-only
  authentication:
    method: ServiceAccountToken
    serviceAccountTokenSettings:
      audience: aio-mq
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: mq-to-mq
  namespace: azure-iot-operations
spec:
  profileRef: profile
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq
        dataSources:
        - azure-iot-operations/data/thermostat
    - operationType: destination
      name: destination1
      destinationSettings:
        endpointRef: mq
        dataDestination: thermostat-copy